spring.application.name=servicea

logging.level.root=INFO
logging.level.com.logdetective.servicea=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always