spring.application.name=serviceb
server.port=8081
service.a.url=${SERVICE_A_URL:http://service-a:8080/tasks}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always